Add support for passive data connection through NAT with PASV command
aio-libs/aioftp pull request #150
Opened 2022-03-17 08:56 UTC by janneronkko

This allows old FTP client to connect to AIOFtp server located behind
NAT.

## What do these changes do?

The change adds support for clients using passive connections (PASV command) to a server located behind NAT

## Are there changes in behavior for the user?

Passive connections can be opened with PASV command to server behind (IPv4) NAT

## Related issue number

N/A

## Checklist

- [x ] I think the code is well written
- [x ] Unit tests for the changes exist
- [x ] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder -- *there is no CHANGES folder*
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

2022-03-17 09:00 UTC, janneronkko commented
I faced this issue with a service I've implemented; all the clients connecting to our service do not use EPSV command (using EPSV would have worked)

2022-03-17 22:03 UTC, pohmelie requested changes

2022-03-18 07:13 UTC, janneronkko commented on aioftp/server.py
> +                 external_ipv4_address=None,
Except that the value must be IPv4 address so the "response_host_name" is misleading in my opinion.

Anway it is now updated to use that as the name.

2022-03-18 08:17 UTC, pohmelie commented on aioftp/server.py
> +                 external_ipv4_address=None,
Oh, yes, I missed the ipv4 thing. Then something like `ipv4_pasv_forced_response_host_name`.

2022-03-18 08:49 UTC, janneronkko commented on aioftp/server.py
> +                 external_ipv4_address=None,
Still the hostname can be, for example, ftp.example.org but the response for PASV command is IPv4 address (and port)

That is the reason I used `external_ipv4_address` originally.

So if I change the name to `ipv4_pasv_forced_response_host_name` that is the final name for this?

2022-03-18 08:56 UTC, pohmelie commented on aioftp/server.py
> +                 external_ipv4_address=None,
I aggree with you. `ipv4_pasv_forced_response_address` LGTM.

2022-03-18 11:21 UTC, merged

2022-03-18 11:27 UTC, pohmelie commented
Thank you for the PR, released as 0.21.0.